app:
  pgURL: 'postgres://bvvlrxtlondxai:ApbcroxVZjWX0kzYBlEOhcHA4P@ec2-54-235-250-41.compute-1.amazonaws.com:5432/d8lfu06ln72uv1'
  pg:
    database:
    username:
    password:
    host:
    dialect:
    port:
  port: 10010
  query:
    pageSize: 20
    onlyRootMessages: false
